import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1723076724619 implements MigrationInterface {
    name = 'Init1723076724619';

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "offer" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "is_delete" boolean NOT NULL DEFAULT false, "posit" character varying, "sport" character varying, "paused" boolean, "sexo" character varying NOT NULL, "category" character varying NOT NULL, "province" character varying, "urgency" integer, "retribution" boolean NOT NULL, "prop1" json, "prop2" json, "matches" text, "prop4" text, "inscriptions" text, "club_id" uuid, CONSTRAINT "PK_57c6ae1abe49201919ef68de900" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "skill" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "is_delete" boolean NOT NULL DEFAULT false, "info" text NOT NULL, "prop1" json, "prop2" json, "prop3" text, "prop4" text, CONSTRAINT "PK_a0d33334424e64fb78dc3ce7196" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sport" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "is_delete" boolean NOT NULL DEFAULT false, "name" character varying NOT NULL, "img" character varying, "prop1" json, "prop2" json, "prop3" text, "prop4" text, "club_id" uuid, CONSTRAINT "UQ_6a16e1d83cb581484036cee92bf" UNIQUE ("name"), CONSTRAINT "PK_c67275331afac347120a1032825" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "position" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "is_delete" boolean NOT NULL DEFAULT false, "name" character varying NOT NULL, "prop1" json, "prop2" json, "prop3" text, "prop4" text, "club_id" uuid, "sport_id" uuid, CONSTRAINT "PK_b7f483581562b4dc62ae1a5b7e2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."sportman_type_enum" AS ENUM('player', 'coach', 'invitado')`);
        await queryRunner.query(`CREATE TABLE "sportman" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "is_delete" boolean NOT NULL DEFAULT false, "type" "public"."sportman_type_enum" NOT NULL DEFAULT 'player', "info" text NOT NULL, "prop1" json, "prop2" json, "prop3" text, "prop4" text, "user_id" uuid, "club_id" uuid, "sport_id" uuid, "skill_id" uuid, "position_id" uuid, CONSTRAINT "REL_d0aae5b254c67da2190884c3bf" UNIQUE ("user_id"), CONSTRAINT "REL_918631b5a1a3cf26dd3999a4d3" UNIQUE ("skill_id"), CONSTRAINT "PK_731064ef97d7fbd9577e1230ac2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "match" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "is_delete" boolean NOT NULL DEFAULT false, "status" character varying, "prop1" json, "prop2" json, "prop3" text, "prop4" text, "offer_id_id" uuid, CONSTRAINT "PK_92b6c3a6631dd5b24a67c69f69d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "club" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "is_delete" boolean NOT NULL DEFAULT false, "name" character varying NOT NULL, "city" character varying NOT NULL, "country" character varying NOT NULL, "field" character varying NOT NULL, "sport" character varying, "year" integer NOT NULL, "capacity" integer NOT NULL, "description" character varying, "img_perfil" character varying, "img_front" character varying, "prop1" json, "prop2" json, "prop3" text, "prop4" text, "user_id" uuid, CONSTRAINT "REL_6c8136b34bb2aee2a28e682d7e" UNIQUE ("user_id"), CONSTRAINT "PK_79282481e036a6e0b180afa38aa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "post" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "is_delete" boolean NOT NULL DEFAULT false, "image" text NOT NULL, "description" character varying NOT NULL, "likes" integer NOT NULL DEFAULT '0', "comment_count" integer NOT NULL DEFAULT '0', "prop1" json, "prop2" json, "prop3" text, "prop4" text, "author_type" character varying NOT NULL, "author_id" uuid, CONSTRAINT "PK_be5fda3aac270b134ff9c21cdee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "comment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "is_delete" boolean NOT NULL DEFAULT false, "content" character varying NOT NULL, "prop1" json, "prop2" json, "prop3" text, "prop4" text, "author_id" uuid, "post_id" uuid, CONSTRAINT "PK_0b0e4bbc8415ec426f87f3a88e2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "like" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "is_delete" boolean NOT NULL DEFAULT false, "prop1" json, "prop2" json, "prop3" text, "prop4" text, "author_id" uuid, "post_id" uuid, CONSTRAINT "PK_eff3e46d24d416b52a7e0ae4159" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_type_enum" AS ENUM('sportman', 'club', 'invitado')`);
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "is_delete" boolean NOT NULL DEFAULT false, "nickname" character varying NOT NULL, "email" character varying, "google_id" character varying, "facebook_id" character varying, "apple_id" character varying, "stripe_id" character varying NOT NULL DEFAULT '', "password" character varying, "type" "public"."user_type_enum" NOT NULL, "plan" character varying NOT NULL DEFAULT 'basic', "plan_id" character varying DEFAULT '', "prop1" json, "prop2" json, "following" text, "followers" text, "prop3" text, "prop4" text, "club_id" uuid, "sportman_id" uuid, CONSTRAINT "REL_4f89a8eafafbd7c3193dcff66d" UNIQUE ("club_id"), CONSTRAINT "REL_5aad327088de71eb0cd6e086b8" UNIQUE ("sportman_id"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "resetCode" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "is_delete" boolean NOT NULL DEFAULT false, "code" character varying NOT NULL, "email" character varying NOT NULL, "expires_at" TIMESTAMP NOT NULL, CONSTRAINT "UQ_b0956d865317a9a14e8a6ffce8a" UNIQUE ("email"), CONSTRAINT "PK_60ab9f1d23c69c361b73aaf5bf4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notification" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "is_delete" boolean NOT NULL DEFAULT false, "title" character varying NOT NULL, "message" character varying NOT NULL, "date" TIMESTAMP NOT NULL, "recipient_id" character varying NOT NULL, "read" boolean DEFAULT false, "prop1" json, "prop2" json, "prop3" text, "prop4" text, CONSTRAINT "PK_705b6c7cdf9b2c2ff7ac7872cb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "message" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "is_delete" boolean NOT NULL DEFAULT false, "sender_id" character varying NOT NULL, "receiver_id" character varying NOT NULL, "room" character varying NOT NULL, "message" character varying NOT NULL, "is_readed" boolean NOT NULL DEFAULT false, "sender_delete" boolean, "receiver_delete" boolean, "prop1" json, "prop2" json, "prop3" text, "prop4" text, CONSTRAINT "PK_ba01f0a3e0123651915008bc578" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sportman_matches_match" ("sportman_id" uuid NOT NULL, "match_id" uuid NOT NULL, CONSTRAINT "PK_da0de742d1bde300505668d5515" PRIMARY KEY ("sportman_id", "match_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9e2ca8c783bae5ff710d1b0cc3" ON "sportman_matches_match" ("sportman_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_29787f42b5290b10959cc45984" ON "sportman_matches_match" ("match_id") `);
        await queryRunner.query(`CREATE TABLE "match_sportmen_id_sportman" ("match_id" uuid NOT NULL, "sportman_id" uuid NOT NULL, CONSTRAINT "PK_0887d078dd3ed493a37f883db35" PRIMARY KEY ("match_id", "sportman_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_94f7c8b78e110d8e1c756512a3" ON "match_sportmen_id_sportman" ("match_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7ba66a649183f3a8c792b247bb" ON "match_sportmen_id_sportman" ("sportman_id") `);
        await queryRunner.query(`CREATE TABLE "match_club_id_club" ("match_id" uuid NOT NULL, "club_id" uuid NOT NULL, CONSTRAINT "PK_fe5d47cc79bafb2a8d8eec45ca4" PRIMARY KEY ("match_id", "club_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_66b451264d2d9abb02b8c17724" ON "match_club_id_club" ("match_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1224f38bc177300c56b95a07cf" ON "match_club_id_club" ("club_id") `);
        await queryRunner.query(`CREATE TABLE "club_matches_match" ("club_id" uuid NOT NULL, "match_id" uuid NOT NULL, CONSTRAINT "PK_e15ff9eaf7a647927146149d8fd" PRIMARY KEY ("club_id", "match_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9d7e134f6320462277b3934d6c" ON "club_matches_match" ("club_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_392471b823c5eb6a03161a2d56" ON "club_matches_match" ("match_id") `);
        await queryRunner.query(`ALTER TABLE "offer" ADD CONSTRAINT "FK_c7453a5676997ea5adf4dd365cc" FOREIGN KEY ("club_id") REFERENCES "club"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sport" ADD CONSTRAINT "FK_78f4f1358fb8f1d88e54a354c93" FOREIGN KEY ("club_id") REFERENCES "club"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "position" ADD CONSTRAINT "FK_0f90ed1ce1a2e2c361680038efa" FOREIGN KEY ("club_id") REFERENCES "club"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "position" ADD CONSTRAINT "FK_501e77052d76bb76aad6d65b6e6" FOREIGN KEY ("sport_id") REFERENCES "sport"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sportman" ADD CONSTRAINT "FK_d0aae5b254c67da2190884c3bfc" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sportman" ADD CONSTRAINT "FK_0285b46aa2f29fa5993ef20fb79" FOREIGN KEY ("club_id") REFERENCES "club"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sportman" ADD CONSTRAINT "FK_d66a987b59c56b9f2c57c7ee961" FOREIGN KEY ("sport_id") REFERENCES "sport"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sportman" ADD CONSTRAINT "FK_918631b5a1a3cf26dd3999a4d3d" FOREIGN KEY ("skill_id") REFERENCES "skill"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sportman" ADD CONSTRAINT "FK_8cb544f030e6b8a59ee26b85541" FOREIGN KEY ("position_id") REFERENCES "position"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match" ADD CONSTRAINT "FK_bab92e03346755e4c705e5d708a" FOREIGN KEY ("offer_id_id") REFERENCES "offer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "club" ADD CONSTRAINT "FK_6c8136b34bb2aee2a28e682d7e3" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post" ADD CONSTRAINT "FK_2f1a9ca8908fc8168bc18437f62" FOREIGN KEY ("author_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment" ADD CONSTRAINT "FK_3ce66469b26697baa097f8da923" FOREIGN KEY ("author_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment" ADD CONSTRAINT "FK_8aa21186314ce53c5b61a0e8c93" FOREIGN KEY ("post_id") REFERENCES "post"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "like" ADD CONSTRAINT "FK_db3f30270837f6008d1d61562bd" FOREIGN KEY ("author_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "like" ADD CONSTRAINT "FK_d41caa70371e578e2a4791a88ae" FOREIGN KEY ("post_id") REFERENCES "post"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_4f89a8eafafbd7c3193dcff66db" FOREIGN KEY ("club_id") REFERENCES "club"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_5aad327088de71eb0cd6e086b85" FOREIGN KEY ("sportman_id") REFERENCES "sportman"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sportman_matches_match" ADD CONSTRAINT "FK_9e2ca8c783bae5ff710d1b0cc34" FOREIGN KEY ("sportman_id") REFERENCES "sportman"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "sportman_matches_match" ADD CONSTRAINT "FK_29787f42b5290b10959cc459841" FOREIGN KEY ("match_id") REFERENCES "match"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "match_sportmen_id_sportman" ADD CONSTRAINT "FK_94f7c8b78e110d8e1c756512a36" FOREIGN KEY ("match_id") REFERENCES "match"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "match_sportmen_id_sportman" ADD CONSTRAINT "FK_7ba66a649183f3a8c792b247bb8" FOREIGN KEY ("sportman_id") REFERENCES "sportman"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_club_id_club" ADD CONSTRAINT "FK_66b451264d2d9abb02b8c17724f" FOREIGN KEY ("match_id") REFERENCES "match"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "match_club_id_club" ADD CONSTRAINT "FK_1224f38bc177300c56b95a07cf9" FOREIGN KEY ("club_id") REFERENCES "club"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "club_matches_match" ADD CONSTRAINT "FK_9d7e134f6320462277b3934d6c0" FOREIGN KEY ("club_id") REFERENCES "club"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "club_matches_match" ADD CONSTRAINT "FK_392471b823c5eb6a03161a2d567" FOREIGN KEY ("match_id") REFERENCES "match"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "club_matches_match" DROP CONSTRAINT "FK_392471b823c5eb6a03161a2d567"`);
        await queryRunner.query(`ALTER TABLE "club_matches_match" DROP CONSTRAINT "FK_9d7e134f6320462277b3934d6c0"`);
        await queryRunner.query(`ALTER TABLE "match_club_id_club" DROP CONSTRAINT "FK_1224f38bc177300c56b95a07cf9"`);
        await queryRunner.query(`ALTER TABLE "match_club_id_club" DROP CONSTRAINT "FK_66b451264d2d9abb02b8c17724f"`);
        await queryRunner.query(`ALTER TABLE "match_sportmen_id_sportman" DROP CONSTRAINT "FK_7ba66a649183f3a8c792b247bb8"`);
        await queryRunner.query(`ALTER TABLE "match_sportmen_id_sportman" DROP CONSTRAINT "FK_94f7c8b78e110d8e1c756512a36"`);
        await queryRunner.query(`ALTER TABLE "sportman_matches_match" DROP CONSTRAINT "FK_29787f42b5290b10959cc459841"`);
        await queryRunner.query(`ALTER TABLE "sportman_matches_match" DROP CONSTRAINT "FK_9e2ca8c783bae5ff710d1b0cc34"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_5aad327088de71eb0cd6e086b85"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_4f89a8eafafbd7c3193dcff66db"`);
        await queryRunner.query(`ALTER TABLE "like" DROP CONSTRAINT "FK_d41caa70371e578e2a4791a88ae"`);
        await queryRunner.query(`ALTER TABLE "like" DROP CONSTRAINT "FK_db3f30270837f6008d1d61562bd"`);
        await queryRunner.query(`ALTER TABLE "comment" DROP CONSTRAINT "FK_8aa21186314ce53c5b61a0e8c93"`);
        await queryRunner.query(`ALTER TABLE "comment" DROP CONSTRAINT "FK_3ce66469b26697baa097f8da923"`);
        await queryRunner.query(`ALTER TABLE "post" DROP CONSTRAINT "FK_2f1a9ca8908fc8168bc18437f62"`);
        await queryRunner.query(`ALTER TABLE "club" DROP CONSTRAINT "FK_6c8136b34bb2aee2a28e682d7e3"`);
        await queryRunner.query(`ALTER TABLE "match" DROP CONSTRAINT "FK_bab92e03346755e4c705e5d708a"`);
        await queryRunner.query(`ALTER TABLE "sportman" DROP CONSTRAINT "FK_8cb544f030e6b8a59ee26b85541"`);
        await queryRunner.query(`ALTER TABLE "sportman" DROP CONSTRAINT "FK_918631b5a1a3cf26dd3999a4d3d"`);
        await queryRunner.query(`ALTER TABLE "sportman" DROP CONSTRAINT "FK_d66a987b59c56b9f2c57c7ee961"`);
        await queryRunner.query(`ALTER TABLE "sportman" DROP CONSTRAINT "FK_0285b46aa2f29fa5993ef20fb79"`);
        await queryRunner.query(`ALTER TABLE "sportman" DROP CONSTRAINT "FK_d0aae5b254c67da2190884c3bfc"`);
        await queryRunner.query(`ALTER TABLE "position" DROP CONSTRAINT "FK_501e77052d76bb76aad6d65b6e6"`);
        await queryRunner.query(`ALTER TABLE "position" DROP CONSTRAINT "FK_0f90ed1ce1a2e2c361680038efa"`);
        await queryRunner.query(`ALTER TABLE "sport" DROP CONSTRAINT "FK_78f4f1358fb8f1d88e54a354c93"`);
        await queryRunner.query(`ALTER TABLE "offer" DROP CONSTRAINT "FK_c7453a5676997ea5adf4dd365cc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_392471b823c5eb6a03161a2d56"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9d7e134f6320462277b3934d6c"`);
        await queryRunner.query(`DROP TABLE "club_matches_match"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1224f38bc177300c56b95a07cf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_66b451264d2d9abb02b8c17724"`);
        await queryRunner.query(`DROP TABLE "match_club_id_club"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7ba66a649183f3a8c792b247bb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_94f7c8b78e110d8e1c756512a3"`);
        await queryRunner.query(`DROP TABLE "match_sportmen_id_sportman"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_29787f42b5290b10959cc45984"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9e2ca8c783bae5ff710d1b0cc3"`);
        await queryRunner.query(`DROP TABLE "sportman_matches_match"`);
        await queryRunner.query(`DROP TABLE "message"`);
        await queryRunner.query(`DROP TABLE "notification"`);
        await queryRunner.query(`DROP TABLE "resetCode"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TYPE "public"."user_type_enum"`);
        await queryRunner.query(`DROP TABLE "like"`);
        await queryRunner.query(`DROP TABLE "comment"`);
        await queryRunner.query(`DROP TABLE "post"`);
        await queryRunner.query(`DROP TABLE "club"`);
        await queryRunner.query(`DROP TABLE "match"`);
        await queryRunner.query(`DROP TABLE "sportman"`);
        await queryRunner.query(`DROP TYPE "public"."sportman_type_enum"`);
        await queryRunner.query(`DROP TABLE "position"`);
        await queryRunner.query(`DROP TABLE "sport"`);
        await queryRunner.query(`DROP TABLE "skill"`);
        await queryRunner.query(`DROP TABLE "offer"`);
    }

}
